# -*- coding: utf-8 -*-
"""pw_2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ty_bqqF8jOZnHsSuZojYIoBaVT_GVGae
"""

a = 1202
print(a)
print(bin(a))
print(oct(a))
print(hex(a))




#task 1
b = 45

print(bin(b))
print(oct(b))
print(hex(b))